package TK.game.EntityStuff.AlienStuff;

public enum AlienType {
    SECTOID, DRONE, THINMAN, FLOATER, OUTSIDER, CHRYSSALID, MUTON, HEAVYFLOATER, CYBERDISC, MUTONELITE, BERSERKER,
    SECTOIDCOMMANDER, ETHEREAL, SECTOPOD, UBERETHEREAL;
}
